# Generated by Django 3.2.6 on 2024-05-05 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('IdEmpresa', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Empresa', models.CharField(default='', max_length=50, verbose_name='Empresa')),
                ('Url_img', models.CharField(default='', max_length=50, null=True, verbose_name='Ruta de imagen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('IdRegion', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_region', models.CharField(default='', max_length=50, verbose_name='Region')),
                ('Ubicacion', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Ubicación')),
                ('Telefono', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('Correo', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('fk_IdEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('IdSucursal', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_sucursal', models.CharField(default='', max_length=50, verbose_name='Sucursal')),
                ('Ubicacion', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('Telefono', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('Correo', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('Is_active', models.BooleanField(default=True)),
                ('Ruta_img', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='img')),
                ('fk_IdRegion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rl_user_company',
            fields=[
                ('IdRelacion', models.AutoField(primary_key=True, serialize=False)),
                ('fk_IdEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('fk_IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rl_sucursal_licencia',
            fields=[
                ('Id_relacion', models.AutoField(primary_key=True, serialize=False)),
                ('fk_IdLicencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.licencia')),
                ('fk_IdSucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='config_web_empresa',
            fields=[
                ('IdConfig', models.AutoField(primary_key=True, serialize=False)),
                ('Element_fila', models.CharField(blank=True, max_length=2, null=True, verbose_name='Elementos por fila')),
                ('Color_estable', models.CharField(blank=True, max_length=8, null=True, verbose_name='Color estable')),
                ('Color_advertencia', models.CharField(blank=True, max_length=8, null=True, verbose_name='Color advertencia')),
                ('Color_urgencia', models.CharField(blank=True, max_length=8, null=True, verbose_name='Color urgencia')),
                ('fk_IdEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Area_trabajo',
            fields=[
                ('IdArea', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_zona', models.CharField(default='', max_length=50)),
                ('Is_active', models.BooleanField(default=True)),
                ('fk_IdSucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.sucursal')),
            ],
        ),
    ]
