# Generated by Django 3.2.6 on 2024-05-13 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_region_fk_idempresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config_web_empresa',
            name='fk_IdEmpresa',
        ),
        migrations.AddField(
            model_name='company',
            name='fk_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.config_web_empresa'),
        ),
    ]
