# Generated by Django 3.2.6 on 2024-05-15 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_url_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='fk_IdRegion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.region'),
        ),
    ]
