# Generated by Django 3.2.6 on 2024-05-15 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_region_url_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='Url_img',
            new_name='ImagenEmpresa',
        ),
    ]
