# Generated by Django 3.2.6 on 2024-05-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_rename_url_img_region_imagenempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ClaveEmpresa',
            field=models.CharField(default='', max_length=64, verbose_name='Clave'),
        ),
    ]
