# Generated by Django 3.2.6 on 2024-05-16 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_area_trabajo_fk_idsucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_trabajo',
            name='fk_IdSucursal',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='company.sucursal'),
        ),
    ]
