# Generated by Django 3.2.6 on 2024-05-17 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0013_auto_20240516_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rl_usuario_sucursal',
            fields=[
                ('IdRelacion', models.AutoField(primary_key=True, serialize=False)),
                ('fk_IdSucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.sucursal')),
                ('fk_IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
