# Generated by Django 3.2.6 on 2024-05-19 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_rl_usuario_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='Is_active',
        ),
        migrations.AlterField(
            model_name='area_trabajo',
            name='fk_IdSucursal',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.sucursal'),
        ),
        migrations.AlterField(
            model_name='region',
            name='fk_IdEmpresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.company'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='fk_IdRegion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.region'),
        ),
    ]
