# Generated by Django 3.2.6 on 2024-05-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('IdLicencia', models.AutoField(primary_key=True, serialize=False)),
                ('Licencia', models.CharField(default='', max_length=100, verbose_name='Licencia')),
                ('Fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('Fecha_vencimiento', models.DateTimeField(verbose_name='Fecha de vencimiento')),
                ('Estado_licencia', models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido'), ('por_vencer', 'Por Vencer'), ('disponible', 'Disponible')], default='disponible', max_length=50)),
                ('Is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
