# Generated by Django 3.2.6 on 2024-05-05 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='config_tipo_sensor',
            fields=[
                ('IdTipo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(blank=True, default='', max_length=50)),
                ('Tipo_dato', models.CharField(blank='', default='', max_length=5, null='')),
                ('Icono', models.CharField(default='', max_length=50, null=True)),
                ('Indice_widget', models.CharField(default='', max_length=5)),
                ('Rango_registros', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('Rango_tiempo', models.CharField(default='', max_length=20)),
                ('Rango_max', models.CharField(default='', max_length=20)),
                ('Rango_min', models.CharField(default='', max_length=20)),
                ('fk_IdUSer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dispositivo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('IdDispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('Modelo', models.CharField(default='', max_length=10)),
                ('MAC', models.CharField(default='', max_length=12)),
                ('Estado', models.CharField(choices=[('habilitado', 'Habilitado'), ('deshabilitado', 'Deshabilitado'), ('nuevo', 'Nuevo')], default='nuevo', max_length=15)),
                ('IdArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.area_trabajo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('IdSensor', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Nombre')),
                ('Licencia_sensor', models.CharField(default='', max_length=50)),
                ('IsAlive', models.BooleanField(default=True)),
                ('Estado', models.CharField(choices=[('habilitado', 'Habilitado'), ('deshabilitado', 'Deshabilitado')], default='habilitado', max_length=15)),
                ('fk_IdDispositivo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sensors.dispositivo')),
                ('fk_IdTipo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sensors.config_tipo_sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='registro_incidencias',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('IdRegistro', models.BigAutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('fk_IdSensor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensors.sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('IdRegistro', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('fk_IdSensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
