# Generated by Django 3.2.6 on 2024-05-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='MAC',
            field=models.CharField(default='', max_length=20),
        ),
    ]
