# Generated by Django 3.2.6 on 2024-05-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_dispositivo_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='Modelo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
