# Generated by Django 3.2.6 on 2024-05-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_dispositivo_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Valor',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
