# Generated by Django 3.2.6 on 2024-05-17 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20240516_1741'),
        ('sensors', '0004_alter_register_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='fk_IdEmpresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
