# Generated by Django 3.2.6 on 2024-05-19 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20240519_1004'),
        ('sensors', '0005_dispositivo_fk_idempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='IdArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.area_trabajo'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='fk_IdEmpresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.company'),
        ),
        migrations.AlterField(
            model_name='register',
            name='fk_IdSensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensors.sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='fk_IdDispositivo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='sensors.dispositivo'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='fk_IdTipo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='sensors.config_tipo_sensor'),
        ),
    ]
